#!/usr/bin/env python3

import urllib.request
import json
import socket
import time
import re
from lxml import etree

def getHtml4Url(url):
    print('>>>>>>>>>>start getHtml4Url')
    num = 1
    while True:
        if num > 10:
            return "access fail for ten times"
        try:
            with urllib.request.urlopen(url, timeout=10) as response:
                text = response.read().decode('utf-8')
                num = 1
                return etree.HTML(text, etree.HTMLParser())
        except urllib.error.URLError as e:
            print(e)
            num += 1
        except socket.timeout as e:
            print(e)
            num += 1
        except Exception as e:
            print(e)
            num += 1

def getJson4Url(url):
    print('>>>>>>>>>>start getJson4Url')
    num = 1
    while True:
        if num > 10:
            return "access fail for ten times"
        try:
            with urllib.request.urlopen(url, timeout=10) as response:
                num = 1
                return response.read().decode('utf-8')
        except urllib.error.URLError as e:
            print(e)
            num += 1
        except socket.timeout as e:
            print(e)
            num += 1
        except Exception as e:
            print(e)
            num += 1
